(cl:defpackage t1-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "THREEINTS"
   "<THREEINTS-REQUEST>"
   "THREEINTS-REQUEST"
   "<THREEINTS-RESPONSE>"
   "THREEINTS-RESPONSE"
  ))

